api/workspace/v1alpha1/config.go, internal/controllers/user_controller.go, internal/controllers/user_controller_test.go, internal/controllers/workspace_controller.go, internal/controllers/workspace_controller_test.go
=> Fix workspace instance vars

internal/webhooks/user_webhook.go, internal/webhooks/user_webhook_test.go
=> Add user name check

api/openapi/dashboard/v1alpha1/api_auth.go, api/openapi/dashboard/v1alpha1/api_user.go, api/openapi/dashboard/v1alpha1/api_workspace.go, api/openapi/dashboard/v1alpha1/routers.go, hack/api-generate/go-server/routers.mustache, hack/api-generate/openapitools.json, hack/api-generate/package.json, hack/api-generate/yarn.lock, web/dashboard-ui/src/api/dashboard/v1alpha1/api.ts, web/dashboard-ui/src/api/dashboard/v1alpha1/base.ts, web/dashboard-ui/src/api/dashboard/v1alpha1/common.ts
Uncontrolled data used in path expression
api/openapi/dashboard/v1alpha1/routers.go:120 
```
file, err := ioutil.TempFile("", fileHeader.Filename)
```
=> Resolve security alert

pkg/template/unstructured.go, pkg/template/unstructured_test.go
=> #69 cannot generate Template including '---'

server_test.go, suite_test.go
=> Add dashboard server test

api/core/v1alpha1/instance_types.go, api/core/v1alpha1/template_types.go, example/eks-irsa-useraddon.yaml, internal/cmd/template/generate.go, internal/cmd/template/get.go, internal/controllers/template_controller.go, internal/controllers/template_controller_test.go, internal/controllers/user_controller_test.go, internal/controllers/workspace_controller_test.go, internal/webhooks/instance_webhook_test.go, internal/webhooks/template_webhook_test.go, internal/webhooks/user_webhook.go, internal/webhooks/user_webhook_test.go, internal/webhooks/workspace_webhook_test.go, pkg/kosmo/client.go, pkg/kosmo/client_test.go, pkg/template/label.go, pkg/template/label_test.go, pkg/transformer/metadata.go, pkg/transformer/metadata_test.go, pkg/transformer/utils_test.go, pkg/wscfg/config.go, pkg/wscfg/config_test.go
=> Feature disable name prefix

internal/dashboard/template_handler.go, internal/dashboard/user_handler.go, internal/dashboard/workspace_handler.go
close #182 Sort the list items that respond from the dashboard API
=> Sort the list items that respond from the dashboard API

api/openapi/dashboard/openapi-v1alpha1.yaml, api/openapi/dashboard/v1alpha1/model_update_user_role_request.go, internal/dashboard/user_handler_test.go, web/dashboard-ui/src/api/dashboard/v1alpha1/api.ts
close #133 unable to delete user role
=> unable to delete user role

api/openapi/dashboard/openapi-v1alpha1.yaml, api/openapi/dashboard/v1alpha1/model_network_rule.go, api/openapi/dashboard/v1alpha1/model_upsert_network_rule_request.go, internal/dashboard/workspace_handler_test.go, internal/dashboard/workspace_network_handler.go, web/dashboard-ui/src/api/dashboard/v1alpha1/api.ts, web/dashboard-ui/src/views/organisms/NetworkRuleActionDialog.tsx, web/dashboard-ui/src/views/organisms/WorkspaceModule.tsx, web/dashboard-ui/src/views/pages/WorkspacePage.tsx
=>  Support public network rule in Dashboard

hack/api-generate/yarn.lock, web/auth-proxy-ui/yarn.lock, web/dashboard-ui/src/__tests__/views/atoms/__snapshots__/PasswordTextField.spec.tsx.snap, web/dashboard-ui/src/__tests__/views/atoms/__snapshots__/TextFieldLabel.spec.tsx.snap, web/dashboard-ui/src/__tests__/views/organisms/__snapshots__/PasswordChangeDialog.spec.tsx.snap, web/dashboard-ui/src/__tests__/views/organisms/__snapshots__/UserNameChangeDialog.spec.tsx.snap, web/dashboard-ui/yarn.lock
update yarn.lock. Update dependent packages to the latest version.
Updated UI test snapshot files.
=> update package & UI test snapshot files

.github/release-drafter.yml, .github/workflows/release-drafter.yml
=> Create release note automatically

internal/dashboard/workspace_handler_test.go, internal/dashboard/workspace_network_handler.go
=> Sort network rule list items that respond from the dashboard API 

internal/dashboard/workspace_handler.go, internal/dashboard/workspace_handler_test.go
=> If ws.Spec.Replicas returns nil, set it to "1"

Makefile, charts/cosmo-controller-manager/templates/webhook.yaml
=> fix indent

internal/cmd/__snapshots__/workspace_test.snap, internal/cmd/workspace/close_port.go, internal/cmd/workspace/create.go, internal/cmd/workspace/delete.go, internal/cmd/workspace/open_port.go, pkg/cmdutil/options.go
=> [cosmoctl] fix type 'all-namespace' -> 'all-namespaces'

api/workspace/v1alpha1/workspace_types.go, internal/authproxy/__snapshots__/reconciler_test.snap, internal/authproxy/proxy/manager.go, internal/authproxy/public/index.html, internal/authproxy/reconciler.go, internal/authproxy/reconciler_test.go, internal/authproxy/suite_test.go, pkg/kosmo/test/test_util.go
- Fix:sometimes wrong Proxy is shutdown in GC
- Fix:target port number is not updated
- Fix:proxy server is not shutdown when all network rules are deleted
- Fix:target port is not initialized when changed to public
=> [auth-proxy] Fix bugs in auth-proxy reconcile

Makefile, hack/local-run-test/Makefile, internal/cmd/__snapshots__/template_test.snap, internal/cmd/__snapshots__/user_test.snap, internal/cmd/__snapshots__/workspace_test.snap, internal/cmd/workspace_test.go
- Update envtest to v1.21.x
- Recfactoring cosmoctl test
- Modify makefile for build  cosmoctl on local-run-test
=> Chore:Update envtest to v1.21.x, test code refactoring ,etc.

internal/webhooks/__snapshots__/workspace_webhook_test.snap, internal/webhooks/workspace_webhook.go, internal/webhooks/workspace_webhook_test.go
=> PortName should be limited less than 15 characters

internal/dashboard/__snapshots__/user_handler_test.snap, internal/dashboard/user_handler.go, internal/dashboard/user_handler_test.go
=> [dashboard]Prevent deletion of own user

internal/cmd/__snapshots__/user_test.snap, internal/cmd/user/create.go, internal/cmd/user_test.go
before
```
cosmoctl user create ...  \
--addons temple1,temple2 \
--addon-vars Addon=temple1,key11=xxxx,key12=yyy,Addon=temple2,key21=xxxx,key22=yyy
```
after
```
cosmoctl user create ...  \
--addon user-temple1,key11=xxxx,key12=yyy \
--addon user-temple2,key21=xxxx,key22=yyy
```
- close #357
=> [cosmoctl] Modify addon flag

hack/local-run-test/Makefile, web/dashboard-ui/src/views/organisms/UserActionDialog.tsx
=> [Dashboard UI] Fix default user addon checkbox not effective

hack/local-run-test/Makefile, web/dashboard-ui/src/views/organisms/UserActionDialog.tsx
=> Fix:[Dashboard UI] default user addon is not sent to the server

Makefile, internal/authproxy/reconciler_test.go, internal/authproxy/suite_test.go, internal/cmd/suite_test.go, internal/cmd/template_test.go, internal/cmd/user_test.go, internal/cmd/workspace_test.go, internal/controllers/__snapshots__/cluster_instance_controller_test.snap, internal/controllers/__snapshots__/instance_controller_test.snap, internal/controllers/__snapshots__/template_controller_test.snap, internal/controllers/cluster_instance_controller.go, internal/controllers/cluster_instance_controller_test.go, internal/controllers/instance_controller.go, internal/controllers/instance_controller_test.go, internal/controllers/suite_test.go, internal/controllers/template_controller_test.go, internal/controllers/workspace_status_controller.go, internal/dashboard/suite_test.go, internal/webhooks/suite_test.go, pkg/auth/password/suite_test.go, pkg/cmdutil/options_test.go, pkg/kosmo/suite_test.go, pkg/kubeutil/client_mock.go, pkg/kubeutil/suite_test.go
=> Fix controller manager bugs

charts/cosmo-controller-manager/templates/manager.yaml, cmd/controller-manager/main.go
=> [controller-manager]Support port number change

api/openapi/dashboard/v1alpha1/auth_request_impl.go, hack/api-generate/Makefile, hack/api-generate/go-server/auth_request_impl.go_, hack/proxy-driver/main.go, internal/dashboard/auth_handler.go, pkg/auth/authorizer.go, pkg/auth/dashboard_authorizer.go, pkg/auth/password_secret_authorizer.go
=> Fix authorizer package to use AuthRequest interface

hack/local-run-test/Makefile
=> Fix: local run test failed with traefik helm install error

internal/dashboard/__snapshots__/template_handler_test.snap, internal/dashboard/template_handler.go, internal/dashboard/template_handler_test.go
=> Fix: Normal User cannot get workspace templates

web/dashboard-ui/src/__tests__/views/pages/SignIn.spec.tsx, web/dashboard-ui/src/views/pages/SignIn.tsx, web/dashboard-ui/src/views/templates/PageTemplate.tsx
feature: auto redirect from signin page when already signed in like https://github.com/login
- redirect automatically from signin page when already signed in
- validate redirect url whether it domain is the same as current domain
- if invalid redirect url, show error
- update error boundary view
=> feature: auto redirect from signin page when already signed in

charts/cosmo-dashboard/templates/ingress.yaml, charts/cosmo-traefik/templates/cosmo-auth-middleware.yaml, charts/cosmo-traefik/values.yaml, hack/local-run-test/templates/code-server-01/cosmo-template.yaml, hack/local-run-test/templates/code-server-01/kubernetes/network.yaml, internal/cmd/template/workspace.go, internal/controllers/__snapshots__/workspace_controller_test.snap, pkg/workspace/__snapshots__/workspace_test.snap, pkg/workspace/workspace.go
=> traefik v3: change traefik.containo.us to traefik.io

web/dashboard-ui/src/views/organisms/UserActionDialog.tsx
- UserAddon tooltip does not work
- UserAddon collapse works wired when Template has no required vars
=> Fix: UI bugs

internal/controllers/__snapshots__/cluster_instance_controller_test.snap, internal/controllers/__snapshots__/user_controller_test.snap, internal/controllers/cluster_instance_controller_test.go, internal/controllers/instance_controller.go, internal/controllers/user_controller.go, internal/controllers/user_controller_test.go
close #724
close #729
improve tests
=> fix controller bugs

internal/controllers/cluster_instance_controller_test.go, internal/controllers/cluster_template_controller_test.go, internal/controllers/instance_controller_test.go, internal/controllers/template_controller_test.go, internal/controllers/user_controller_test.go, internal/webhooks/__snapshots__/instance_webhook_test.snap, internal/webhooks/__snapshots__/template_webhook_test.snap, internal/webhooks/instance_webhook.go, internal/webhooks/instance_webhook_test.go, internal/webhooks/template_webhook.go, internal/webhooks/template_webhook_test.go, pkg/kubeutil/test/snap/snap.go
=> improvements for webhooks

api/v1alpha1/utils.go, api/v1alpha1/utils_test.go, pkg/auth/password/password.go
=> Add label `cosmo-workspace.github.io/controller-managed` on password secret

internal/dashboard/__snapshots__/user_handler_test.snap, internal/dashboard/auth_middleware.go, internal/dashboard/auth_middleware_test.go, internal/dashboard/user_handler.go, internal/dashboard/user_sub_handler.go, web/dashboard-ui/src/views/pages/WorkspacePage.tsx
=> Not to show UserSelect component for *-admin users

Makefile, hack/local-run-test/Makefile, web/dashboard-ui/package.json, web/dashboard-ui/src/__tests__/components/AuthRoute.spec.tsx, web/dashboard-ui/src/__tests__/views/organisms/PasswordChangeDialog.spec.tsx, web/dashboard-ui/src/__tests__/views/organisms/UserModule.spec.tsx, web/dashboard-ui/src/__tests__/views/organisms/UserNameChangeDialog.spec.tsx, web/dashboard-ui/src/__tests__/views/organisms/WorkspaceModule.spec.tsx, web/dashboard-ui/src/components/LoginProvider.tsx, web/dashboard-ui/src/services/DashboardServices.ts, web/dashboard-ui/src/views/organisms/UserModule.tsx, web/dashboard-ui/src/views/organisms/WorkspaceModule.tsx, web/dashboard-ui/vite.config.ts, web/dashboard-ui/yarn.lock
=> Fix: Incorrect error in dashbord after session timeout

web/dashboard-ui/src/views/templates/PageTemplate.tsx
=> Disable change password button when auth type is not 'password-secret'

api/v1alpha1/user_types.go, api/v1alpha1/user_types_test.go
=> Support group-admin is admin for group

web/dashboard-ui/src/App.tsx, web/dashboard-ui/src/__tests__/views/organisms/__snapshots__/UserModule.spec.tsx.snap, web/dashboard-ui/src/__tests__/views/organisms/__snapshots__/WorkspaceModule.spec.tsx.snap, web/dashboard-ui/src/views/organisms/UserActionDialog.tsx, web/dashboard-ui/src/views/templates/PageTemplate.tsx
Close #798
- Show my user info dialog for all user
- Add change addon menu on admin app bar
=> Improve UI about UserAddon infomation

docs/THIRD-PARTY-LICENCE.md, web/dashboard-ui/package.json, web/dashboard-ui/src/views/pages/UserPage.tsx, web/dashboard-ui/src/views/pages/WorkspacePage.tsx, web/dashboard-ui/yarn.lock
=> keep search string and filter roles state in URL param

internal/controllers/workspace_status_controller.go
=> Backoff for next reconciliation

internal/controllers/user_controller.go, internal/controllers/workspace_controller.go
=> Not to emit the event of "object has been modified"

web/dashboard-ui/src/views/organisms/WorkspaceModule.tsx, web/dashboard-ui/src/views/pages/WorkspacePage.tsx
- fix updateClock timing
- stop polling if user changed
=> Fix UI small bugs

web/dashboard-ui/src/views/atoms/EllipsisTypography.tsx, web/dashboard-ui/src/views/atoms/NameAvatar.tsx, web/dashboard-ui/src/views/organisms/NetworkRuleActionDialog.tsx, web/dashboard-ui/src/views/organisms/UserActionDialog.tsx, web/dashboard-ui/src/views/organisms/UserAddonsChangeDialog.tsx, web/dashboard-ui/src/views/organisms/WorkspaceModule.tsx, web/dashboard-ui/src/views/pages/EventPage.tsx, web/dashboard-ui/src/views/pages/UserPage.tsx, web/dashboard-ui/src/views/templates/PageTemplate.tsx
Close #828
Related #833 as client side paginations
=> Use MUI DataGrid for User page
